#!/usr/bin/env python
#
# Copyright 2010, 2011 Robert Schroll
#
# This file is part of SlideDeX and is distributed under the terms of
# the BSD license.  See the file COPYING for full details.
#
######################################################################

import os
import sys
import gtk

from slidedex import misc
from slidedex.latexdocument import LatexDocument

if len(sys.argv) > 1:
    filename = sys.argv[1]
else:
    filename = None
doc = LatexDocument(filename)
